method: grid
parameters:
  n_samples:
    values: [100, 200, 500]
  n_continuous_features:
    values: [10, 15]
  n_discrete_features:
    values: [10, 15]
  n_classes:
    values: [2, 3]
  class_distribution:
    values: [[0.7, 0.3], [0.5, 0.5]]
  n_bins:
    values: [5, 10]
  n_redundant:
    values: [5, 10]
  n_noisy:
    values: [10, 20]
  class_sep:
    values: [0.1, 0.5]
  model_name:
    values: ["nn", "xgboost", "modernbert"]

program: train_models.py
